### ISSUE TITLE
Big notification when process is finished 

### ISSUE THREAD

**Issue by ftiff** [macadmins/SplashBuddy#55]
For Labs, adding an optional big notification would allow better visual control of the status of the process.

**Comment by HowardGMac** [comment]
You could for example have an optional preference in the SplashBuddy.plist called `labEnvironment` that when set to true would hide the sidebar and direct the webview to a complete.html page in the presentation.bundle once all of the application installations were completed.

**Comment by ftiff** [comment]
that should have been closed ages ago. It was implemented in 1.2

* With `labMode` set to `true`, SplashBuddy will automatically display `complete.html` from `presentation.bundle` when all software is done installing (successfully or not) -- thank you @howardgmac
